// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4AVceC8QNJm6nVh0JusPnbLWhp0lCOM',
    appId: '1:704477939372:web:322cdb091614d121cd0109',
    messagingSenderId: '704477939372',
    projectId: 'mobile-payement-app',
    authDomain: 'mobile-payement-app.firebaseapp.com',
    storageBucket: 'mobile-payement-app.appspot.com',
    measurementId: 'G-1DXRHGV3MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASF119P5zib-HUwPkI1gVxtyzuabiakX8',
    appId: '1:704477939372:android:08a1c2e461ef1daacd0109',
    messagingSenderId: '704477939372',
    projectId: 'mobile-payement-app',
    storageBucket: 'mobile-payement-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AAlg0T61hiuOPBZkaAI--EptxKdupR8',
    appId: '1:704477939372:ios:dcd86f8451628bc4cd0109',
    messagingSenderId: '704477939372',
    projectId: 'mobile-payement-app',
    storageBucket: 'mobile-payement-app.appspot.com',
    iosBundleId: 'com.example.mobilePayementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AAlg0T61hiuOPBZkaAI--EptxKdupR8',
    appId: '1:704477939372:ios:dcd86f8451628bc4cd0109',
    messagingSenderId: '704477939372',
    projectId: 'mobile-payement-app',
    storageBucket: 'mobile-payement-app.appspot.com',
    iosBundleId: 'com.example.mobilePayementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs4AVceC8QNJm6nVh0JusPnbLWhp0lCOM',
    appId: '1:704477939372:web:7714439bba2c9a9dcd0109',
    messagingSenderId: '704477939372',
    projectId: 'mobile-payement-app',
    authDomain: 'mobile-payement-app.firebaseapp.com',
    storageBucket: 'mobile-payement-app.appspot.com',
    measurementId: 'G-THEWBK1L9C',
  );
}
